// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: fillyengine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EngineService_StartEngine_FullMethodName     = "/fillyengine.EngineService/StartEngine"
	EngineService_StopEngine_FullMethodName      = "/fillyengine.EngineService/StopEngine"
	EngineService_LoadModel_FullMethodName       = "/fillyengine.EngineService/LoadModel"
	EngineService_GetStatus_FullMethodName       = "/fillyengine.EngineService/GetStatus"
	EngineService_ListLocalModels_FullMethodName = "/fillyengine.EngineService/ListLocalModels"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EngineServiceClient interface {
	StartEngine(ctx context.Context, in *StartEngineRequest, opts ...grpc.CallOption) (*EngineStatus, error)
	StopEngine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStatus, error)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*EngineStatus, error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStatus, error)
	ListLocalModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) StartEngine(ctx context.Context, in *StartEngineRequest, opts ...grpc.CallOption) (*EngineStatus, error) {
	out := new(EngineStatus)
	err := c.cc.Invoke(ctx, EngineService_StartEngine_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) StopEngine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStatus, error) {
	out := new(EngineStatus)
	err := c.cc.Invoke(ctx, EngineService_StopEngine_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*EngineStatus, error) {
	out := new(EngineStatus)
	err := c.cc.Invoke(ctx, EngineService_LoadModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EngineStatus, error) {
	out := new(EngineStatus)
	err := c.cc.Invoke(ctx, EngineService_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ListLocalModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error) {
	out := new(ModelList)
	err := c.cc.Invoke(ctx, EngineService_ListLocalModels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility
type EngineServiceServer interface {
	StartEngine(context.Context, *StartEngineRequest) (*EngineStatus, error)
	StopEngine(context.Context, *Empty) (*EngineStatus, error)
	LoadModel(context.Context, *LoadModelRequest) (*EngineStatus, error)
	GetStatus(context.Context, *Empty) (*EngineStatus, error)
	ListLocalModels(context.Context, *Empty) (*ModelList, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEngineServiceServer struct {
}

func (UnimplementedEngineServiceServer) StartEngine(context.Context, *StartEngineRequest) (*EngineStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartEngine not implemented")
}
func (UnimplementedEngineServiceServer) StopEngine(context.Context, *Empty) (*EngineStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopEngine not implemented")
}
func (UnimplementedEngineServiceServer) LoadModel(context.Context, *LoadModelRequest) (*EngineStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedEngineServiceServer) GetStatus(context.Context, *Empty) (*EngineStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEngineServiceServer) ListLocalModels(context.Context, *Empty) (*ModelList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLocalModels not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_StartEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).StartEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_StartEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).StartEngine(ctx, req.(*StartEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_StopEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).StopEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_StopEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).StopEngine(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ListLocalModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ListLocalModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ListLocalModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ListLocalModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fillyengine.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartEngine",
			Handler:    _EngineService_StartEngine_Handler,
		},
		{
			MethodName: "StopEngine",
			Handler:    _EngineService_StopEngine_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _EngineService_LoadModel_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _EngineService_GetStatus_Handler,
		},
		{
			MethodName: "ListLocalModels",
			Handler:    _EngineService_ListLocalModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fillyengine.proto",
}

const (
	ChatService_CreateSession_FullMethodName = "/fillyengine.ChatService/CreateSession"
	ChatService_SendMessage_FullMethodName   = "/fillyengine.ChatService/SendMessage"
	ChatService_StreamMessage_FullMethodName = "/fillyengine.ChatService/StreamMessage"
	ChatService_GetHistory_FullMethodName    = "/fillyengine.ChatService/GetHistory"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	SendMessage(ctx context.Context, in *ChatMessageRequest, opts ...grpc.CallOption) (*ChatMessageResponse, error)
	// Server-Streaming für Token-für-Token Antworten
	StreamMessage(ctx context.Context, in *ChatMessageRequest, opts ...grpc.CallOption) (ChatService_StreamMessageClient, error)
	GetHistory(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*ChatHistory, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, ChatService_CreateSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *ChatMessageRequest, opts ...grpc.CallOption) (*ChatMessageResponse, error) {
	out := new(ChatMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_SendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) StreamMessage(ctx context.Context, in *ChatMessageRequest, opts ...grpc.CallOption) (ChatService_StreamMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_StreamMessage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceStreamMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_StreamMessageClient interface {
	Recv() (*ChatToken, error)
	grpc.ClientStream
}

type chatServiceStreamMessageClient struct {
	grpc.ClientStream
}

func (x *chatServiceStreamMessageClient) Recv() (*ChatToken, error) {
	m := new(ChatToken)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) GetHistory(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*ChatHistory, error) {
	out := new(ChatHistory)
	err := c.cc.Invoke(ctx, ChatService_GetHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*SessionInfo, error)
	SendMessage(context.Context, *ChatMessageRequest) (*ChatMessageResponse, error)
	// Server-Streaming für Token-für-Token Antworten
	StreamMessage(*ChatMessageRequest, ChatService_StreamMessageServer) error
	GetHistory(context.Context, *SessionRequest) (*ChatHistory, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedChatServiceServer) SendMessage(context.Context, *ChatMessageRequest) (*ChatMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServiceServer) StreamMessage(*ChatMessageRequest, ChatService_StreamMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessage not implemented")
}
func (UnimplementedChatServiceServer) GetHistory(context.Context, *SessionRequest) (*ChatHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*ChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_StreamMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).StreamMessage(m, &chatServiceStreamMessageServer{stream})
}

type ChatService_StreamMessageServer interface {
	Send(*ChatToken) error
	grpc.ServerStream
}

type chatServiceStreamMessageServer struct {
	grpc.ServerStream
}

func (x *chatServiceStreamMessageServer) Send(m *ChatToken) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetHistory(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fillyengine.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _ChatService_CreateSession_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _ChatService_GetHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessage",
			Handler:       _ChatService_StreamMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fillyengine.proto",
}

const (
	TrainingService_StartTraining_FullMethodName  = "/fillyengine.TrainingService/StartTraining"
	TrainingService_GetJobStatus_FullMethodName   = "/fillyengine.TrainingService/GetJobStatus"
	TrainingService_ListJobs_FullMethodName       = "/fillyengine.TrainingService/ListJobs"
	TrainingService_CancelJob_FullMethodName      = "/fillyengine.TrainingService/CancelJob"
	TrainingService_StreamProgress_FullMethodName = "/fillyengine.TrainingService/StreamProgress"
)

// TrainingServiceClient is the client API for TrainingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingServiceClient interface {
	StartTraining(ctx context.Context, in *TrainingRequest, opts ...grpc.CallOption) (*JobInfo, error)
	GetJobStatus(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error)
	ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobList, error)
	CancelJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error)
	// Server-Streaming für Live-Training-Metriken
	StreamProgress(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (TrainingService_StreamProgressClient, error)
}

type trainingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingServiceClient(cc grpc.ClientConnInterface) TrainingServiceClient {
	return &trainingServiceClient{cc}
}

func (c *trainingServiceClient) StartTraining(ctx context.Context, in *TrainingRequest, opts ...grpc.CallOption) (*JobInfo, error) {
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, TrainingService_StartTraining_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) GetJobStatus(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, TrainingService_GetJobStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobList, error) {
	out := new(JobList)
	err := c.cc.Invoke(ctx, TrainingService_ListJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) CancelJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, TrainingService_CancelJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingServiceClient) StreamProgress(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (TrainingService_StreamProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &TrainingService_ServiceDesc.Streams[0], TrainingService_StreamProgress_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &trainingServiceStreamProgressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TrainingService_StreamProgressClient interface {
	Recv() (*TrainingMetrics, error)
	grpc.ClientStream
}

type trainingServiceStreamProgressClient struct {
	grpc.ClientStream
}

func (x *trainingServiceStreamProgressClient) Recv() (*TrainingMetrics, error) {
	m := new(TrainingMetrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrainingServiceServer is the server API for TrainingService service.
// All implementations must embed UnimplementedTrainingServiceServer
// for forward compatibility
type TrainingServiceServer interface {
	StartTraining(context.Context, *TrainingRequest) (*JobInfo, error)
	GetJobStatus(context.Context, *JobRequest) (*JobStatus, error)
	ListJobs(context.Context, *Empty) (*JobList, error)
	CancelJob(context.Context, *JobRequest) (*JobStatus, error)
	// Server-Streaming für Live-Training-Metriken
	StreamProgress(*JobRequest, TrainingService_StreamProgressServer) error
	mustEmbedUnimplementedTrainingServiceServer()
}

// UnimplementedTrainingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrainingServiceServer struct {
}

func (UnimplementedTrainingServiceServer) StartTraining(context.Context, *TrainingRequest) (*JobInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTraining not implemented")
}
func (UnimplementedTrainingServiceServer) GetJobStatus(context.Context, *JobRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedTrainingServiceServer) ListJobs(context.Context, *Empty) (*JobList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedTrainingServiceServer) CancelJob(context.Context, *JobRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedTrainingServiceServer) StreamProgress(*JobRequest, TrainingService_StreamProgressServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedTrainingServiceServer) mustEmbedUnimplementedTrainingServiceServer() {}

// UnsafeTrainingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingServiceServer will
// result in compilation errors.
type UnsafeTrainingServiceServer interface {
	mustEmbedUnimplementedTrainingServiceServer()
}

func RegisterTrainingServiceServer(s grpc.ServiceRegistrar, srv TrainingServiceServer) {
	s.RegisterService(&TrainingService_ServiceDesc, srv)
}

func _TrainingService_StartTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).StartTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_StartTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).StartTraining(ctx, req.(*TrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).GetJobStatus(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).ListJobs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).CancelJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingService_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrainingServiceServer).StreamProgress(m, &trainingServiceStreamProgressServer{stream})
}

type TrainingService_StreamProgressServer interface {
	Send(*TrainingMetrics) error
	grpc.ServerStream
}

type trainingServiceStreamProgressServer struct {
	grpc.ServerStream
}

func (x *trainingServiceStreamProgressServer) Send(m *TrainingMetrics) error {
	return x.ServerStream.SendMsg(m)
}

// TrainingService_ServiceDesc is the grpc.ServiceDesc for TrainingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fillyengine.TrainingService",
	HandlerType: (*TrainingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTraining",
			Handler:    _TrainingService_StartTraining_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _TrainingService_GetJobStatus_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _TrainingService_ListJobs_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _TrainingService_CancelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProgress",
			Handler:       _TrainingService_StreamProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fillyengine.proto",
}

const (
	QuantizationService_StartQuantization_FullMethodName = "/fillyengine.QuantizationService/StartQuantization"
	QuantizationService_GetJobStatus_FullMethodName      = "/fillyengine.QuantizationService/GetJobStatus"
	QuantizationService_ListJobs_FullMethodName          = "/fillyengine.QuantizationService/ListJobs"
	QuantizationService_GetAvailableTypes_FullMethodName = "/fillyengine.QuantizationService/GetAvailableTypes"
	QuantizationService_StreamProgress_FullMethodName    = "/fillyengine.QuantizationService/StreamProgress"
)

// QuantizationServiceClient is the client API for QuantizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuantizationServiceClient interface {
	StartQuantization(ctx context.Context, in *QuantRequest, opts ...grpc.CallOption) (*JobInfo, error)
	GetJobStatus(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error)
	ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobList, error)
	GetAvailableTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuantTypes, error)
	// Streaming Progress
	StreamProgress(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (QuantizationService_StreamProgressClient, error)
}

type quantizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantizationServiceClient(cc grpc.ClientConnInterface) QuantizationServiceClient {
	return &quantizationServiceClient{cc}
}

func (c *quantizationServiceClient) StartQuantization(ctx context.Context, in *QuantRequest, opts ...grpc.CallOption) (*JobInfo, error) {
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, QuantizationService_StartQuantization_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantizationServiceClient) GetJobStatus(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, QuantizationService_GetJobStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantizationServiceClient) ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobList, error) {
	out := new(JobList)
	err := c.cc.Invoke(ctx, QuantizationService_ListJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantizationServiceClient) GetAvailableTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuantTypes, error) {
	out := new(QuantTypes)
	err := c.cc.Invoke(ctx, QuantizationService_GetAvailableTypes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantizationServiceClient) StreamProgress(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (QuantizationService_StreamProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuantizationService_ServiceDesc.Streams[0], QuantizationService_StreamProgress_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &quantizationServiceStreamProgressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QuantizationService_StreamProgressClient interface {
	Recv() (*QuantProgress, error)
	grpc.ClientStream
}

type quantizationServiceStreamProgressClient struct {
	grpc.ClientStream
}

func (x *quantizationServiceStreamProgressClient) Recv() (*QuantProgress, error) {
	m := new(QuantProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QuantizationServiceServer is the server API for QuantizationService service.
// All implementations must embed UnimplementedQuantizationServiceServer
// for forward compatibility
type QuantizationServiceServer interface {
	StartQuantization(context.Context, *QuantRequest) (*JobInfo, error)
	GetJobStatus(context.Context, *JobRequest) (*JobStatus, error)
	ListJobs(context.Context, *Empty) (*JobList, error)
	GetAvailableTypes(context.Context, *Empty) (*QuantTypes, error)
	// Streaming Progress
	StreamProgress(*JobRequest, QuantizationService_StreamProgressServer) error
	mustEmbedUnimplementedQuantizationServiceServer()
}

// UnimplementedQuantizationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuantizationServiceServer struct {
}

func (UnimplementedQuantizationServiceServer) StartQuantization(context.Context, *QuantRequest) (*JobInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartQuantization not implemented")
}
func (UnimplementedQuantizationServiceServer) GetJobStatus(context.Context, *JobRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedQuantizationServiceServer) ListJobs(context.Context, *Empty) (*JobList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedQuantizationServiceServer) GetAvailableTypes(context.Context, *Empty) (*QuantTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableTypes not implemented")
}
func (UnimplementedQuantizationServiceServer) StreamProgress(*JobRequest, QuantizationService_StreamProgressServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedQuantizationServiceServer) mustEmbedUnimplementedQuantizationServiceServer() {}

// UnsafeQuantizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantizationServiceServer will
// result in compilation errors.
type UnsafeQuantizationServiceServer interface {
	mustEmbedUnimplementedQuantizationServiceServer()
}

func RegisterQuantizationServiceServer(s grpc.ServiceRegistrar, srv QuantizationServiceServer) {
	s.RegisterService(&QuantizationService_ServiceDesc, srv)
}

func _QuantizationService_StartQuantization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantizationServiceServer).StartQuantization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantizationService_StartQuantization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantizationServiceServer).StartQuantization(ctx, req.(*QuantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantizationService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantizationServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantizationService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantizationServiceServer).GetJobStatus(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantizationService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantizationServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantizationService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantizationServiceServer).ListJobs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantizationService_GetAvailableTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantizationServiceServer).GetAvailableTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantizationService_GetAvailableTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantizationServiceServer).GetAvailableTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantizationService_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuantizationServiceServer).StreamProgress(m, &quantizationServiceStreamProgressServer{stream})
}

type QuantizationService_StreamProgressServer interface {
	Send(*QuantProgress) error
	grpc.ServerStream
}

type quantizationServiceStreamProgressServer struct {
	grpc.ServerStream
}

func (x *quantizationServiceStreamProgressServer) Send(m *QuantProgress) error {
	return x.ServerStream.SendMsg(m)
}

// QuantizationService_ServiceDesc is the grpc.ServiceDesc for QuantizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuantizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fillyengine.QuantizationService",
	HandlerType: (*QuantizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartQuantization",
			Handler:    _QuantizationService_StartQuantization_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _QuantizationService_GetJobStatus_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _QuantizationService_ListJobs_Handler,
		},
		{
			MethodName: "GetAvailableTypes",
			Handler:    _QuantizationService_GetAvailableTypes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProgress",
			Handler:       _QuantizationService_StreamProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fillyengine.proto",
}

const (
	MarktplatzService_Search_FullMethodName                 = "/fillyengine.MarktplatzService/Search"
	MarktplatzService_GetModelDetail_FullMethodName         = "/fillyengine.MarktplatzService/GetModelDetail"
	MarktplatzService_Download_FullMethodName               = "/fillyengine.MarktplatzService/Download"
	MarktplatzService_StreamDownloadProgress_FullMethodName = "/fillyengine.MarktplatzService/StreamDownloadProgress"
)

// MarktplatzServiceClient is the client API for MarktplatzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarktplatzServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetModelDetail(ctx context.Context, in *ModelDetailRequest, opts ...grpc.CallOption) (*ModelDetail, error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*JobInfo, error)
	// Streaming Download-Progress
	StreamDownloadProgress(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (MarktplatzService_StreamDownloadProgressClient, error)
}

type marktplatzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarktplatzServiceClient(cc grpc.ClientConnInterface) MarktplatzServiceClient {
	return &marktplatzServiceClient{cc}
}

func (c *marktplatzServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MarktplatzService_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marktplatzServiceClient) GetModelDetail(ctx context.Context, in *ModelDetailRequest, opts ...grpc.CallOption) (*ModelDetail, error) {
	out := new(ModelDetail)
	err := c.cc.Invoke(ctx, MarktplatzService_GetModelDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marktplatzServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*JobInfo, error) {
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, MarktplatzService_Download_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marktplatzServiceClient) StreamDownloadProgress(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (MarktplatzService_StreamDownloadProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarktplatzService_ServiceDesc.Streams[0], MarktplatzService_StreamDownloadProgress_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &marktplatzServiceStreamDownloadProgressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarktplatzService_StreamDownloadProgressClient interface {
	Recv() (*DownloadProgress, error)
	grpc.ClientStream
}

type marktplatzServiceStreamDownloadProgressClient struct {
	grpc.ClientStream
}

func (x *marktplatzServiceStreamDownloadProgressClient) Recv() (*DownloadProgress, error) {
	m := new(DownloadProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MarktplatzServiceServer is the server API for MarktplatzService service.
// All implementations must embed UnimplementedMarktplatzServiceServer
// for forward compatibility
type MarktplatzServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetModelDetail(context.Context, *ModelDetailRequest) (*ModelDetail, error)
	Download(context.Context, *DownloadRequest) (*JobInfo, error)
	// Streaming Download-Progress
	StreamDownloadProgress(*JobRequest, MarktplatzService_StreamDownloadProgressServer) error
	mustEmbedUnimplementedMarktplatzServiceServer()
}

// UnimplementedMarktplatzServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarktplatzServiceServer struct {
}

func (UnimplementedMarktplatzServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMarktplatzServiceServer) GetModelDetail(context.Context, *ModelDetailRequest) (*ModelDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelDetail not implemented")
}
func (UnimplementedMarktplatzServiceServer) Download(context.Context, *DownloadRequest) (*JobInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedMarktplatzServiceServer) StreamDownloadProgress(*JobRequest, MarktplatzService_StreamDownloadProgressServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamDownloadProgress not implemented")
}
func (UnimplementedMarktplatzServiceServer) mustEmbedUnimplementedMarktplatzServiceServer() {}

// UnsafeMarktplatzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarktplatzServiceServer will
// result in compilation errors.
type UnsafeMarktplatzServiceServer interface {
	mustEmbedUnimplementedMarktplatzServiceServer()
}

func RegisterMarktplatzServiceServer(s grpc.ServiceRegistrar, srv MarktplatzServiceServer) {
	s.RegisterService(&MarktplatzService_ServiceDesc, srv)
}

func _MarktplatzService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarktplatzServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarktplatzService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarktplatzServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarktplatzService_GetModelDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarktplatzServiceServer).GetModelDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarktplatzService_GetModelDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarktplatzServiceServer).GetModelDetail(ctx, req.(*ModelDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarktplatzService_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarktplatzServiceServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarktplatzService_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarktplatzServiceServer).Download(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarktplatzService_StreamDownloadProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarktplatzServiceServer).StreamDownloadProgress(m, &marktplatzServiceStreamDownloadProgressServer{stream})
}

type MarktplatzService_StreamDownloadProgressServer interface {
	Send(*DownloadProgress) error
	grpc.ServerStream
}

type marktplatzServiceStreamDownloadProgressServer struct {
	grpc.ServerStream
}

func (x *marktplatzServiceStreamDownloadProgressServer) Send(m *DownloadProgress) error {
	return x.ServerStream.SendMsg(m)
}

// MarktplatzService_ServiceDesc is the grpc.ServiceDesc for MarktplatzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarktplatzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fillyengine.MarktplatzService",
	HandlerType: (*MarktplatzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _MarktplatzService_Search_Handler,
		},
		{
			MethodName: "GetModelDetail",
			Handler:    _MarktplatzService_GetModelDetail_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _MarktplatzService_Download_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDownloadProgress",
			Handler:       _MarktplatzService_StreamDownloadProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fillyengine.proto",
}

const (
	SkillsService_ListSkills_FullMethodName   = "/fillyengine.SkillsService/ListSkills"
	SkillsService_ImportSkill_FullMethodName  = "/fillyengine.SkillsService/ImportSkill"
	SkillsService_UpdateSkill_FullMethodName  = "/fillyengine.SkillsService/UpdateSkill"
	SkillsService_DeleteSkill_FullMethodName  = "/fillyengine.SkillsService/DeleteSkill"
	SkillsService_RescanSkills_FullMethodName = "/fillyengine.SkillsService/RescanSkills"
)

// SkillsServiceClient is the client API for SkillsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkillsServiceClient interface {
	ListSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillListResponse, error)
	ImportSkill(ctx context.Context, in *ImportSkillRequest, opts ...grpc.CallOption) (*SkillResponse, error)
	UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*SkillResponse, error)
	DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillResponse, error)
	RescanSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillListResponse, error)
}

type skillsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillsServiceClient(cc grpc.ClientConnInterface) SkillsServiceClient {
	return &skillsServiceClient{cc}
}

func (c *skillsServiceClient) ListSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillListResponse, error) {
	out := new(SkillListResponse)
	err := c.cc.Invoke(ctx, SkillsService_ListSkills_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillsServiceClient) ImportSkill(ctx context.Context, in *ImportSkillRequest, opts ...grpc.CallOption) (*SkillResponse, error) {
	out := new(SkillResponse)
	err := c.cc.Invoke(ctx, SkillsService_ImportSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillsServiceClient) UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*SkillResponse, error) {
	out := new(SkillResponse)
	err := c.cc.Invoke(ctx, SkillsService_UpdateSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillsServiceClient) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillResponse, error) {
	out := new(DeleteSkillResponse)
	err := c.cc.Invoke(ctx, SkillsService_DeleteSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillsServiceClient) RescanSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillListResponse, error) {
	out := new(SkillListResponse)
	err := c.cc.Invoke(ctx, SkillsService_RescanSkills_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillsServiceServer is the server API for SkillsService service.
// All implementations must embed UnimplementedSkillsServiceServer
// for forward compatibility
type SkillsServiceServer interface {
	ListSkills(context.Context, *Empty) (*SkillListResponse, error)
	ImportSkill(context.Context, *ImportSkillRequest) (*SkillResponse, error)
	UpdateSkill(context.Context, *UpdateSkillRequest) (*SkillResponse, error)
	DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillResponse, error)
	RescanSkills(context.Context, *Empty) (*SkillListResponse, error)
	mustEmbedUnimplementedSkillsServiceServer()
}

// UnimplementedSkillsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkillsServiceServer struct {
}

func (UnimplementedSkillsServiceServer) ListSkills(context.Context, *Empty) (*SkillListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedSkillsServiceServer) ImportSkill(context.Context, *ImportSkillRequest) (*SkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSkill not implemented")
}
func (UnimplementedSkillsServiceServer) UpdateSkill(context.Context, *UpdateSkillRequest) (*SkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSkill not implemented")
}
func (UnimplementedSkillsServiceServer) DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSkill not implemented")
}
func (UnimplementedSkillsServiceServer) RescanSkills(context.Context, *Empty) (*SkillListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RescanSkills not implemented")
}
func (UnimplementedSkillsServiceServer) mustEmbedUnimplementedSkillsServiceServer() {}

// UnsafeSkillsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillsServiceServer will
// result in compilation errors.
type UnsafeSkillsServiceServer interface {
	mustEmbedUnimplementedSkillsServiceServer()
}

func RegisterSkillsServiceServer(s grpc.ServiceRegistrar, srv SkillsServiceServer) {
	s.RegisterService(&SkillsService_ServiceDesc, srv)
}

func _SkillsService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillsServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillsService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillsServiceServer).ListSkills(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillsService_ImportSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillsServiceServer).ImportSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillsService_ImportSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillsServiceServer).ImportSkill(ctx, req.(*ImportSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillsService_UpdateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillsServiceServer).UpdateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillsService_UpdateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillsServiceServer).UpdateSkill(ctx, req.(*UpdateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillsService_DeleteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillsServiceServer).DeleteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillsService_DeleteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillsServiceServer).DeleteSkill(ctx, req.(*DeleteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillsService_RescanSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillsServiceServer).RescanSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillsService_RescanSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillsServiceServer).RescanSkills(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillsService_ServiceDesc is the grpc.ServiceDesc for SkillsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fillyengine.SkillsService",
	HandlerType: (*SkillsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSkills",
			Handler:    _SkillsService_ListSkills_Handler,
		},
		{
			MethodName: "ImportSkill",
			Handler:    _SkillsService_ImportSkill_Handler,
		},
		{
			MethodName: "UpdateSkill",
			Handler:    _SkillsService_UpdateSkill_Handler,
		},
		{
			MethodName: "DeleteSkill",
			Handler:    _SkillsService_DeleteSkill_Handler,
		},
		{
			MethodName: "RescanSkills",
			Handler:    _SkillsService_RescanSkills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fillyengine.proto",
}

const (
	PhiloxAgenticService_ExecuteAgentic_FullMethodName = "/fillyengine.PhiloxAgenticService/ExecuteAgentic"
	PhiloxAgenticService_PlanAgentic_FullMethodName    = "/fillyengine.PhiloxAgenticService/PlanAgentic"
	PhiloxAgenticService_ListTools_FullMethodName      = "/fillyengine.PhiloxAgenticService/ListTools"
)

// PhiloxAgenticServiceClient is the client API for PhiloxAgenticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhiloxAgenticServiceClient interface {
	// Agentic Execution mit Streaming (Tools, Planning, File-Ops)
	ExecuteAgentic(ctx context.Context, in *AgenticRequest, opts ...grpc.CallOption) (PhiloxAgenticService_ExecuteAgenticClient, error)
	// Planning Phase nur (für Approval-Flow)
	PlanAgentic(ctx context.Context, in *AgenticRequest, opts ...grpc.CallOption) (PhiloxAgenticService_PlanAgenticClient, error)
	// Verfügbare Tools für Frontend
	ListTools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolList, error)
}

type philoxAgenticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhiloxAgenticServiceClient(cc grpc.ClientConnInterface) PhiloxAgenticServiceClient {
	return &philoxAgenticServiceClient{cc}
}

func (c *philoxAgenticServiceClient) ExecuteAgentic(ctx context.Context, in *AgenticRequest, opts ...grpc.CallOption) (PhiloxAgenticService_ExecuteAgenticClient, error) {
	stream, err := c.cc.NewStream(ctx, &PhiloxAgenticService_ServiceDesc.Streams[0], PhiloxAgenticService_ExecuteAgentic_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &philoxAgenticServiceExecuteAgenticClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PhiloxAgenticService_ExecuteAgenticClient interface {
	Recv() (*AgenticResponse, error)
	grpc.ClientStream
}

type philoxAgenticServiceExecuteAgenticClient struct {
	grpc.ClientStream
}

func (x *philoxAgenticServiceExecuteAgenticClient) Recv() (*AgenticResponse, error) {
	m := new(AgenticResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *philoxAgenticServiceClient) PlanAgentic(ctx context.Context, in *AgenticRequest, opts ...grpc.CallOption) (PhiloxAgenticService_PlanAgenticClient, error) {
	stream, err := c.cc.NewStream(ctx, &PhiloxAgenticService_ServiceDesc.Streams[1], PhiloxAgenticService_PlanAgentic_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &philoxAgenticServicePlanAgenticClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PhiloxAgenticService_PlanAgenticClient interface {
	Recv() (*AgenticResponse, error)
	grpc.ClientStream
}

type philoxAgenticServicePlanAgenticClient struct {
	grpc.ClientStream
}

func (x *philoxAgenticServicePlanAgenticClient) Recv() (*AgenticResponse, error) {
	m := new(AgenticResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *philoxAgenticServiceClient) ListTools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolList, error) {
	out := new(ToolList)
	err := c.cc.Invoke(ctx, PhiloxAgenticService_ListTools_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhiloxAgenticServiceServer is the server API for PhiloxAgenticService service.
// All implementations must embed UnimplementedPhiloxAgenticServiceServer
// for forward compatibility
type PhiloxAgenticServiceServer interface {
	// Agentic Execution mit Streaming (Tools, Planning, File-Ops)
	ExecuteAgentic(*AgenticRequest, PhiloxAgenticService_ExecuteAgenticServer) error
	// Planning Phase nur (für Approval-Flow)
	PlanAgentic(*AgenticRequest, PhiloxAgenticService_PlanAgenticServer) error
	// Verfügbare Tools für Frontend
	ListTools(context.Context, *Empty) (*ToolList, error)
	mustEmbedUnimplementedPhiloxAgenticServiceServer()
}

// UnimplementedPhiloxAgenticServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPhiloxAgenticServiceServer struct {
}

func (UnimplementedPhiloxAgenticServiceServer) ExecuteAgentic(*AgenticRequest, PhiloxAgenticService_ExecuteAgenticServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteAgentic not implemented")
}
func (UnimplementedPhiloxAgenticServiceServer) PlanAgentic(*AgenticRequest, PhiloxAgenticService_PlanAgenticServer) error {
	return status.Errorf(codes.Unimplemented, "method PlanAgentic not implemented")
}
func (UnimplementedPhiloxAgenticServiceServer) ListTools(context.Context, *Empty) (*ToolList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedPhiloxAgenticServiceServer) mustEmbedUnimplementedPhiloxAgenticServiceServer() {}

// UnsafePhiloxAgenticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhiloxAgenticServiceServer will
// result in compilation errors.
type UnsafePhiloxAgenticServiceServer interface {
	mustEmbedUnimplementedPhiloxAgenticServiceServer()
}

func RegisterPhiloxAgenticServiceServer(s grpc.ServiceRegistrar, srv PhiloxAgenticServiceServer) {
	s.RegisterService(&PhiloxAgenticService_ServiceDesc, srv)
}

func _PhiloxAgenticService_ExecuteAgentic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgenticRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhiloxAgenticServiceServer).ExecuteAgentic(m, &philoxAgenticServiceExecuteAgenticServer{stream})
}

type PhiloxAgenticService_ExecuteAgenticServer interface {
	Send(*AgenticResponse) error
	grpc.ServerStream
}

type philoxAgenticServiceExecuteAgenticServer struct {
	grpc.ServerStream
}

func (x *philoxAgenticServiceExecuteAgenticServer) Send(m *AgenticResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PhiloxAgenticService_PlanAgentic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgenticRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhiloxAgenticServiceServer).PlanAgentic(m, &philoxAgenticServicePlanAgenticServer{stream})
}

type PhiloxAgenticService_PlanAgenticServer interface {
	Send(*AgenticResponse) error
	grpc.ServerStream
}

type philoxAgenticServicePlanAgenticServer struct {
	grpc.ServerStream
}

func (x *philoxAgenticServicePlanAgenticServer) Send(m *AgenticResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PhiloxAgenticService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhiloxAgenticServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhiloxAgenticService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhiloxAgenticServiceServer).ListTools(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PhiloxAgenticService_ServiceDesc is the grpc.ServiceDesc for PhiloxAgenticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhiloxAgenticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fillyengine.PhiloxAgenticService",
	HandlerType: (*PhiloxAgenticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTools",
			Handler:    _PhiloxAgenticService_ListTools_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteAgentic",
			Handler:       _PhiloxAgenticService_ExecuteAgentic_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PlanAgentic",
			Handler:       _PhiloxAgenticService_PlanAgentic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fillyengine.proto",
}
