import '../../core/app_strings.dart' show appLanguage;

const Map<String, String> chatTabsStringsDe = {
  'common.webSearch': 'Websuche',
  'common.realtimeInformation': 'Echtzeit-Informationen',
  'common.planningMode': 'Planungsmodus',
  'common.planningModeHint': 'Erst Plan zur Freigabe, dann Ausfuehrung',
  'common.uploadFile': 'Datei hochladen',
  'common.chooseLocalFile': 'Lokale Datei auswählen',
  'common.web': 'Web',
  'common.thinkingFast': 'Schnell',
  'common.thinkingFastThinking': 'Schnelles Denken',
  'common.thinkingExtra': 'Extra',
  'common.thinkingDual': 'Dual',
  'common.thinkingSpark': 'Spark',
  'common.cancel': 'Abbrechen',
  'common.reject': 'Ablehnen',
  'common.approve': 'Genehmigen',
  'common.edit': 'Bearbeiten',
  'common.copyText': 'Text kopieren',
  'common.actions': 'Aktionen',

  'scout.localReady': 'Lokal • Bereit',
  'scout.loadingModel': 'Modell wird geladen',
  'scout.thinking': 'Scout denkt nach',
  'scout.noActiveChat': 'Kein aktiver Chat',
  'scout.showFileTree': 'Dateibaum anzeigen',
  'scout.modelSwitched': 'Modell gewechselt: {model}',
  'scout.modelSwitchFailed': 'Modellwechsel fehlgeschlagen',
  'scout.startModelFirst':
      'Bitte zuerst ein lokales Engine- oder API-Modell starten',
  'scout.startSessionFailed': 'Chat-Sitzung konnte nicht gestartet werden',
  'scout.newChatStarted': 'Neuer Chat mit {model} gestartet',
  'scout.localModelUnavailable': 'Das lokale Modell ist nicht mehr verfügbar.',
  'scout.modelReady': 'Modell ist bereit',
  'scout.modelStartTimedOut': 'Der Modellstart hat zu lange gewartet.',
  'scout.localModelStartFailed':
      'Das lokale Modell konnte nicht gestartet werden: {error}',
  'scout.chooseAnotherModel': 'Bitte jetzt ein anderes Modell auswählen',
  'scout.settings': 'Einstellungen',
  'scout.localModel': 'Lokales Modell',
  'scout.responseFailed': 'Antwort konnte nicht erzeugt werden',
  'scout.botSavedInManagement':
      '{name} wurde in der Bot-Verwaltung gespeichert',
  'scout.memoryCompressed': 'Memory wurde komprimiert',
  'scout.responseCopied': 'Antwort kopiert',
  'scout.chatPreparing': 'Chat wird vorbereitet …',
  'scout.initializingNewChat': 'Initialisiere neuen Chat…',
  'scout.noModelReady': 'Noch kein Modell bereit',
  'scout.startModelToBegin':
      'Starte ein lokales Engine- oder API-Modell, um loszulegen.',
  'scout.startLocalModel': 'Lokales Modell starten',
  'scout.selectApiModel': 'API-Modell wählen',
  'scout.agentEvent.toolStarted': '{tool} gestartet',
  'scout.agentEvent.toolStartedDefault': 'Tool gestartet',
  'scout.agentEvent.toolFinished': '{tool} beendet',
  'scout.agentEvent.toolFinishedDefault': 'Tool beendet',
  'scout.agentEvent.planningQuestions': 'Planungsfragen',
  'scout.agentEvent.planReady': 'Plan bereit',
  'scout.agentEvent.approvalRequired': 'Freigabe erforderlich',
  'scout.agentEvent.permissionRequested': 'Zugriff außerhalb angefragt',
  'scout.agentEvent.permissionAllowedOnce': 'Zugriff erlaubt (einmalig)',
  'scout.agentEvent.permissionAllowedSession': 'Zugriff erlaubt (Sitzung)',
  'scout.agentEvent.permissionDenied': 'Zugriff abgelehnt',
  'scout.agentEvent.fileCreated': 'Datei erstellt',
  'scout.agentEvent.fileDeleted': 'Datei gelöscht',
  'scout.agentEvent.fileMoved': 'Datei verschoben',
  'scout.agentEvent.fileModified': 'Datei geändert',
  'scout.agentEvent.memoryCompressed': 'Memory komprimiert',
  'scout.files': 'Dateien',
  'scout.refresh': 'Aktualisieren',
  'scout.fileAction.new': 'Neu',
  'scout.fileAction.deleted': 'Gelöscht',
  'scout.fileAction.moved': 'Verschoben',
  'scout.fileAction.modified': 'Geändert',
  'scout.planApproval': 'Planfreigabe',
  'scout.permissionNoLongerOpen': 'Zugriffsanfrage war nicht mehr offen',
  'scout.newBot': 'Neuer Bot',
  'scout.botSaved': '{name} gespeichert',
  'scout.test': 'Testen',
  'scout.editMessageHint': 'Nachricht bearbeiten …',
  'scout.resend': 'Neu senden',
  'scout.jumpToYourMessage': 'Zu deiner Nachricht',
  'scout.shorter': 'Kürzer',
  'scout.moreCritical': 'Kritischer',
  'scout.moreStructure': 'Mehr Struktur',
  'scout.fineTune': 'Feintunen',
  'scout.useAsRule': 'Als Regel',
  'scout.messageHint': 'Nachricht…',
  'scout.addAction': 'Datei oder Chat-Aktion',
  'scout.modelBoundToBot':
      'Das Modell ist fest mit dem ausgewählten Bot verbunden',
  'scout.modelWarming': 'Das Modell läuft gerade warm',
  'scout.voiceMessage': 'Sprachnachricht',
  'scout.selectModelFirst': 'Bitte zuerst ein Modell auswählen',
  'scout.botWorking': 'Scout arbeitet noch …',
  'scout.waitForModel': 'Warten, bis das Modell bereit ist',
  'scout.sendMessage': 'Nachricht senden',
};

const Map<String, String> chatTabsStringsEn = {
  'common.webSearch': 'Web search',
  'common.realtimeInformation': 'Real-time information',
  'common.planningMode': 'Planning mode',
  'common.planningModeHint': 'Plan for approval first, then execution',
  'common.uploadFile': 'Upload file',
  'common.chooseLocalFile': 'Choose local file',
  'common.web': 'Web',
  'common.thinkingFast': 'Fast',
  'common.thinkingFastThinking': 'Fast thinking',
  'common.thinkingExtra': 'Extra',
  'common.thinkingDual': 'Dual',
  'common.thinkingSpark': 'Spark',
  'common.cancel': 'Cancel',
  'common.reject': 'Reject',
  'common.approve': 'Approve',
  'common.edit': 'Edit',
  'common.copyText': 'Copy text',
  'common.actions': 'Actions',

  'scout.localReady': 'Local • Ready',
  'scout.loadingModel': 'Loading model',
  'scout.thinking': 'Scout is thinking',
  'scout.noActiveChat': 'No active chat',
  'scout.showFileTree': 'Show file tree',
  'scout.modelSwitched': 'Model switched: {model}',
  'scout.modelSwitchFailed': 'Could not switch model',
  'scout.startModelFirst': 'Start a local Engine or API model first',
  'scout.startSessionFailed': 'Could not start chat session',
  'scout.newChatStarted': 'New chat started with {model}',
  'scout.localModelUnavailable': 'The local model is no longer available.',
  'scout.modelReady': 'Model is ready',
  'scout.modelStartTimedOut': 'Starting the model took too long.',
  'scout.localModelStartFailed':
      'The local model could not be started: {error}',
  'scout.chooseAnotherModel': 'Choose another model now',
  'scout.settings': 'Settings',
  'scout.localModel': 'Local model',
  'scout.responseFailed': 'Could not generate a response',
  'scout.botSavedInManagement': '{name} was saved in bot management',
  'scout.memoryCompressed': 'Memory was compressed',
  'scout.responseCopied': 'Response copied',
  'scout.chatPreparing': 'Preparing chat …',
  'scout.initializingNewChat': 'Initializing new chat…',
  'scout.noModelReady': 'No model is ready yet',
  'scout.startModelToBegin':
      'Start a local Engine or API model to get started.',
  'scout.startLocalModel': 'Start local model',
  'scout.selectApiModel': 'Select API model',
  'scout.agentEvent.toolStarted': '{tool} started',
  'scout.agentEvent.toolStartedDefault': 'Tool started',
  'scout.agentEvent.toolFinished': '{tool} finished',
  'scout.agentEvent.toolFinishedDefault': 'Tool finished',
  'scout.agentEvent.planningQuestions': 'Planning questions',
  'scout.agentEvent.planReady': 'Plan ready',
  'scout.agentEvent.approvalRequired': 'Approval required',
  'scout.agentEvent.permissionRequested': 'Access requested outside project',
  'scout.agentEvent.permissionAllowedOnce': 'Access allowed once',
  'scout.agentEvent.permissionAllowedSession': 'Access allowed for session',
  'scout.agentEvent.permissionDenied': 'Access denied',
  'scout.agentEvent.fileCreated': 'File created',
  'scout.agentEvent.fileDeleted': 'File deleted',
  'scout.agentEvent.fileMoved': 'File moved',
  'scout.agentEvent.fileModified': 'File changed',
  'scout.agentEvent.memoryCompressed': 'Memory compressed',
  'scout.files': 'Files',
  'scout.refresh': 'Refresh',
  'scout.fileAction.new': 'New',
  'scout.fileAction.deleted': 'Deleted',
  'scout.fileAction.moved': 'Moved',
  'scout.fileAction.modified': 'Changed',
  'scout.planApproval': 'Plan approval',
  'scout.permissionNoLongerOpen': 'The access request was no longer open',
  'scout.newBot': 'New bot',
  'scout.botSaved': '{name} saved',
  'scout.test': 'Test',
  'scout.editMessageHint': 'Edit message …',
  'scout.resend': 'Send again',
  'scout.jumpToYourMessage': 'Go to your message',
  'scout.shorter': 'Shorter',
  'scout.moreCritical': 'More critical',
  'scout.moreStructure': 'More structure',
  'scout.fineTune': 'Fine-tune',
  'scout.useAsRule': 'Use as rule',
  'scout.messageHint': 'Message…',
  'scout.addAction': 'File or chat action',
  'scout.modelBoundToBot': 'The model is fixed to the selected bot',
  'scout.modelWarming': 'The model is warming up',
  'scout.voiceMessage': 'Voice message',
  'scout.selectModelFirst': 'Select a model first',
  'scout.botWorking': 'Scout is still working …',
  'scout.waitForModel': 'Wait until the model is ready',
  'scout.sendMessage': 'Send message',
};

String chatTabsText(String key, [Map<String, String>? params]) {
  final strings = appLanguage == 'en' ? chatTabsStringsEn : chatTabsStringsDe;
  var value = strings[key] ?? chatTabsStringsDe[key] ?? key;
  if (params != null) {
    params.forEach((name, replacement) {
      value = value.replaceAll('{$name}', replacement);
    });
  }
  return value;
}
