import '../../core/app_strings.dart' show appLanguage;

const Map<String, String> chatTabsStringsDe = {
  'common.webSearch': 'Websuche',
  'common.realtimeInformation': 'Echtzeit-Informationen',
  'common.planningMode': 'Planungsmodus',
  'common.planningModeHint': 'Erst Plan zur Freigabe, dann Ausfuehrung',
  'common.planningModeWithSpark': 'Mit Spark immer aktiv',
  'common.uploadFile': 'Datei hochladen',
  'common.chooseLocalFile': 'Lokale Datei auswählen',
  'common.web': 'Web',
  'common.thinkingNone': 'Ohne Reasoning',
  'common.thinkingMinimal': 'Minimal',
  'common.thinkingLow': 'Niedrig',
  'common.thinkingMedium': 'Mittel',
  'common.thinkingHigh': 'Hoch',
  'common.thinkingXHigh': 'Sehr Hoch',
  'common.thinkingMax': 'Maximal',
  'common.thinkingDual': 'Dual',
  'common.modeSpark': 'Spark',
  'common.modeSparkHint': 'Agent mit Werkzeugen und Dateizugriff',
  'common.cancel': 'Abbrechen',
  'common.reject': 'Ablehnen',
  'common.approve': 'Genehmigen',
  'common.edit': 'Bearbeiten',
  'common.copyText': 'Text kopieren',
  'common.actions': 'Aktionen',

  'scout.localReady': 'Lokal • Bereit',
  'scout.loadingModel': 'Modell wird geladen',
  'scout.thinking': 'Scout denkt nach',
  'scout.noActiveChat': 'Kein aktiver Chat',
  'scout.showFileTree': 'Dateibaum anzeigen',
  'scout.modelSwitched': 'Modell gewechselt: {model}',
  'scout.modelSwitchFailed': 'Modellwechsel fehlgeschlagen',
  'scout.startModelFirst':
      'Bitte zuerst ein lokales Engine- oder API-Modell starten',
  'scout.startSessionFailed': 'Chat-Sitzung konnte nicht gestartet werden',
  'scout.newChatStarted': 'Neuer Chat mit {model} gestartet',
  'scout.localModelUnavailable': 'Das lokale Modell ist nicht mehr verfügbar.',
  'scout.modelReady': 'Modell ist bereit',
  'scout.modelStartTimedOut': 'Der Modellstart hat zu lange gewartet.',
  'scout.localModelStartFailed':
      'Das lokale Modell konnte nicht gestartet werden: {error}',
  'scout.chooseAnotherModel': 'Bitte jetzt ein anderes Modell auswählen',
  'scout.settings': 'Einstellungen',
  'scout.localModel': 'Lokales Modell',
  'scout.responseFailed': 'Antwort konnte nicht erzeugt werden',
  'scout.botSavedInManagement':
      '{name} wurde in der Bot-Verwaltung gespeichert',
  'scout.memoryCompressed': 'Memory wurde komprimiert',
  'scout.contextCompacted':
      'Älterer Verlauf wurde zusammengefasst – das Kontextfenster war voll',
  'scout.toolResultsShortened':
      'Ältere Werkzeug-Ergebnisse gekürzt, damit der Lauf im Kontextfenster bleibt',
  'scout.responseCopied': 'Antwort kopiert',
  'scout.chatPreparing': 'Chat wird vorbereitet …',
  'scout.initializingNewChat': 'Initialisiere neuen Chat…',
  'scout.noModelReady': 'Noch kein Modell bereit',
  'scout.startModelToBegin':
      'Starte ein lokales Engine- oder API-Modell, um loszulegen.',
  'scout.startLocalModel': 'Lokales Modell starten',
  'scout.selectApiModel': 'API-Modell wählen',
  'scout.agentEvent.toolStarted': '{tool} gestartet',
  'scout.agentEvent.toolStartedDefault': 'Tool gestartet',
  'scout.agentEvent.toolFinished': '{tool} beendet',
  'scout.agentEvent.toolFinishedDefault': 'Tool beendet',
  'scout.agentEvent.planningQuestions': 'Planungsfragen',
  'scout.agentEvent.planReady': 'Plan bereit',
  'scout.agentEvent.planStarted': 'Abarbeitung gestartet ({total} Schritte)',
  'scout.agentEvent.planStep': 'Schritt {step}/{total}: {title}',
  'scout.agentEvent.planStepDone': 'Schritt {step}/{total} erledigt',
  'scout.agentEvent.planStepFailed': 'Schritt {step}/{total} fehlgeschlagen',
  'scout.agentEvent.planFinished': 'Plan abgearbeitet ({done}/{total})',
  'scout.agentEvent.planSkipped': 'Ohne Plan direkt beantwortet',
  'scout.agentEvent.approvalRequired': 'Freigabe erforderlich',
  'scout.agentEvent.permissionRequested': 'Zugriff außerhalb angefragt',
  'scout.agentEvent.permissionAllowedOnce': 'Zugriff erlaubt (einmalig)',
  'scout.agentEvent.permissionAllowedSession': 'Zugriff erlaubt (Sitzung)',
  'scout.agentEvent.permissionDenied': 'Zugriff abgelehnt',
  'scout.agentEvent.fileCreated': 'Datei erstellt',
  'scout.agentEvent.fileDeleted': 'Datei gelöscht',
  'scout.agentEvent.fileMoved': 'Datei verschoben',
  'scout.agentEvent.fileModified': 'Datei geändert',
  'scout.agentEvent.memoryCompressed': 'Memory komprimiert',
  'scout.files': 'Dateien',
  'scout.refresh': 'Aktualisieren',
  'scout.fileAction.new': 'Neu',
  'scout.fileAction.deleted': 'Gelöscht',
  'scout.fileAction.moved': 'Verschoben',
  'scout.fileAction.modified': 'Geändert',
  'scout.planApproval': 'Planfreigabe',
  'scout.permissionNoLongerOpen': 'Zugriffsanfrage war nicht mehr offen',
  'scout.newBot': 'Neuer Bot',
  'scout.botSaved': '{name} gespeichert',
  'scout.test': 'Testen',
  'scout.editMessageHint': 'Nachricht bearbeiten …',
  'scout.resend': 'Neu senden',
  'scout.jumpToYourMessage': 'Zu deiner Nachricht',
  'scout.shorter': 'Kürzer',
  'scout.moreCritical': 'Kritischer',
  'scout.moreStructure': 'Mehr Struktur',
  'scout.fineTune': 'Feintunen',
  'scout.useAsRule': 'Als Regel',
  'scout.messageHint': 'Nachricht…',
  'scout.addAction': 'Datei oder Chat-Aktion',
  'scout.modelBoundToBot':
      'Das Modell ist fest mit dem ausgewählten Bot verbunden',
  'scout.modelWarming': 'Das Modell läuft gerade warm',
  'scout.voiceMessage': 'Sprachnachricht',
  'scout.selectModelFirst': 'Bitte zuerst ein Modell auswählen',
  'scout.botWorking': 'Scout arbeitet noch …',
  'scout.waitForModel': 'Warten, bis das Modell bereit ist',
  'scout.sendMessage': 'Nachricht senden',
  'scout.multiChat.title': 'Mehrere Chats',
  'scout.multiChat.add': 'Chat hinzufügen',
  'scout.multiChat.new': 'Neuer Chat',
  'scout.multiChat.newHint': 'Mit dem Modell dieses Chat-Fensters starten',
  'scout.multiChat.close': 'Ansicht schließen',
  'scout.multiChat.layout.single': 'Einzelansicht',
  'scout.multiChat.layout.split': 'Zwei Chats',
  'scout.multiChat.layout.grid': 'Vier Chats',
  'scout.multiChat.menuLayout': 'ANSICHT',
  'scout.multiChat.menuAvailable': 'VERFÜGBARE CHATS',
  'scout.multiChat.empty':
      'Wähle einen Chat aus dem Verlauf oder füge ihn hier hinzu.',
  'scout.multiChat.noChatToAdd':
      'Alle verfügbaren Chats sind bereits geöffnet.',
  'scout.multiChat.pane': '{title} – Chat-Fenster',
  'scout.multiChat.reorder': 'Chat an eine andere Position ziehen',
  'scout.multiChat.maximumReached':
      'Es können höchstens vier Chats gleichzeitig geöffnet sein.',
  'scout.multiChat.modelTarget.title': 'Modell für Chat auswählen',
  'scout.multiChat.modelTarget.body':
      'Für welchen geöffneten Chat möchtest du das Modell ändern?',
  'scout.multiChat.modelTarget.current': 'Aktiver Chat',
};

const Map<String, String> chatTabsStringsEn = {
  'common.webSearch': 'Web search',
  'common.realtimeInformation': 'Real-time information',
  'common.planningMode': 'Planning mode',
  'common.planningModeHint': 'Plan for approval first, then execution',
  'common.planningModeWithSpark': 'Always on with Spark',
  'common.uploadFile': 'Upload file',
  'common.chooseLocalFile': 'Choose local file',
  'common.web': 'Web',
  'common.thinkingNone': 'No reasoning',
  'common.thinkingMinimal': 'Minimal',
  'common.thinkingLow': 'Low',
  'common.thinkingMedium': 'Medium',
  'common.thinkingHigh': 'High',
  'common.thinkingXHigh': 'Extra High',
  'common.thinkingMax': 'Max',
  'common.thinkingDual': 'Dual',
  'common.modeSpark': 'Spark',
  'common.modeSparkHint': 'Agent with tools and file access',
  'common.cancel': 'Cancel',
  'common.reject': 'Reject',
  'common.approve': 'Approve',
  'common.edit': 'Edit',
  'common.copyText': 'Copy text',
  'common.actions': 'Actions',

  'scout.localReady': 'Local • Ready',
  'scout.loadingModel': 'Loading model',
  'scout.thinking': 'Scout is thinking',
  'scout.noActiveChat': 'No active chat',
  'scout.showFileTree': 'Show file tree',
  'scout.modelSwitched': 'Model switched: {model}',
  'scout.modelSwitchFailed': 'Could not switch model',
  'scout.startModelFirst': 'Start a local Engine or API model first',
  'scout.startSessionFailed': 'Could not start chat session',
  'scout.newChatStarted': 'New chat started with {model}',
  'scout.localModelUnavailable': 'The local model is no longer available.',
  'scout.modelReady': 'Model is ready',
  'scout.modelStartTimedOut': 'Starting the model took too long.',
  'scout.localModelStartFailed':
      'The local model could not be started: {error}',
  'scout.chooseAnotherModel': 'Choose another model now',
  'scout.settings': 'Settings',
  'scout.localModel': 'Local model',
  'scout.responseFailed': 'Could not generate a response',
  'scout.botSavedInManagement': '{name} was saved in bot management',
  'scout.memoryCompressed': 'Memory was compressed',
  'scout.contextCompacted':
      'Older history was summarised – the context window was full',
  'scout.toolResultsShortened':
      'Older tool results shortened to keep the run inside the context window',
  'scout.responseCopied': 'Response copied',
  'scout.chatPreparing': 'Preparing chat …',
  'scout.initializingNewChat': 'Initializing new chat…',
  'scout.noModelReady': 'No model is ready yet',
  'scout.startModelToBegin':
      'Start a local Engine or API model to get started.',
  'scout.startLocalModel': 'Start local model',
  'scout.selectApiModel': 'Select API model',
  'scout.agentEvent.toolStarted': '{tool} started',
  'scout.agentEvent.toolStartedDefault': 'Tool started',
  'scout.agentEvent.toolFinished': '{tool} finished',
  'scout.agentEvent.toolFinishedDefault': 'Tool finished',
  'scout.agentEvent.planningQuestions': 'Planning questions',
  'scout.agentEvent.planReady': 'Plan ready',
  'scout.agentEvent.planStarted': 'Working the plan ({total} steps)',
  'scout.agentEvent.planStep': 'Step {step}/{total}: {title}',
  'scout.agentEvent.planStepDone': 'Step {step}/{total} done',
  'scout.agentEvent.planStepFailed': 'Step {step}/{total} failed',
  'scout.agentEvent.planFinished': 'Plan worked through ({done}/{total})',
  'scout.agentEvent.planSkipped': 'Answered directly, without a plan',
  'scout.agentEvent.approvalRequired': 'Approval required',
  'scout.agentEvent.permissionRequested': 'Access requested outside project',
  'scout.agentEvent.permissionAllowedOnce': 'Access allowed once',
  'scout.agentEvent.permissionAllowedSession': 'Access allowed for session',
  'scout.agentEvent.permissionDenied': 'Access denied',
  'scout.agentEvent.fileCreated': 'File created',
  'scout.agentEvent.fileDeleted': 'File deleted',
  'scout.agentEvent.fileMoved': 'File moved',
  'scout.agentEvent.fileModified': 'File changed',
  'scout.agentEvent.memoryCompressed': 'Memory compressed',
  'scout.files': 'Files',
  'scout.refresh': 'Refresh',
  'scout.fileAction.new': 'New',
  'scout.fileAction.deleted': 'Deleted',
  'scout.fileAction.moved': 'Moved',
  'scout.fileAction.modified': 'Changed',
  'scout.planApproval': 'Plan approval',
  'scout.permissionNoLongerOpen': 'The access request was no longer open',
  'scout.newBot': 'New bot',
  'scout.botSaved': '{name} saved',
  'scout.test': 'Test',
  'scout.editMessageHint': 'Edit message …',
  'scout.resend': 'Send again',
  'scout.jumpToYourMessage': 'Go to your message',
  'scout.shorter': 'Shorter',
  'scout.moreCritical': 'More critical',
  'scout.moreStructure': 'More structure',
  'scout.fineTune': 'Fine-tune',
  'scout.useAsRule': 'Use as rule',
  'scout.messageHint': 'Message…',
  'scout.addAction': 'File or chat action',
  'scout.modelBoundToBot': 'The model is fixed to the selected bot',
  'scout.modelWarming': 'The model is warming up',
  'scout.voiceMessage': 'Voice message',
  'scout.selectModelFirst': 'Select a model first',
  'scout.botWorking': 'Scout is still working …',
  'scout.waitForModel': 'Wait until the model is ready',
  'scout.sendMessage': 'Send message',
  'scout.multiChat.title': 'Multiple chats',
  'scout.multiChat.add': 'Add chat',
  'scout.multiChat.new': 'New chat',
  'scout.multiChat.newHint': 'Start with this chat pane’s model',
  'scout.multiChat.close': 'Close view',
  'scout.multiChat.layout.single': 'Single view',
  'scout.multiChat.layout.split': 'Two chats',
  'scout.multiChat.layout.grid': 'Four chats',
  'scout.multiChat.menuLayout': 'LAYOUT',
  'scout.multiChat.menuAvailable': 'AVAILABLE CHATS',
  'scout.multiChat.empty': 'Choose a chat from history or add one here.',
  'scout.multiChat.noChatToAdd': 'All available chats are already open.',
  'scout.multiChat.pane': '{title} – chat pane',
  'scout.multiChat.reorder': 'Drag chat to a different position',
  'scout.multiChat.maximumReached':
      'At most four chats can be open at the same time.',
  'scout.multiChat.modelTarget.title': 'Choose chat for model',
  'scout.multiChat.modelTarget.body':
      'Which open chat should the model change apply to?',
  'scout.multiChat.modelTarget.current': 'Active chat',
};

String chatTabsText(String key, [Map<String, String>? params]) {
  final strings = appLanguage == 'en' ? chatTabsStringsEn : chatTabsStringsDe;
  var value = strings[key] ?? chatTabsStringsDe[key] ?? key;
  if (params != null) {
    params.forEach((name, replacement) {
      value = value.replaceAll('{$name}', replacement);
    });
  }
  return value;
}
